name: ecommerce_app_miki
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  intl: ^0.18.0
  flutter_layout_grid: ^2.0.1
  flutter_rating_bar: ^4.0.1
  go_router: ^6.0.0
  flutter_riverpod: ^2.1.3
  shimmer: ^2.0.0
  rxdart: ^0.27.7
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  # needed for the integration tests
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  fonts:
    # Used for Golden Image tests
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

  assets:
    - assets/products/